skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU

build_script:
- msbuild /t:restore /v:m /nologo
- msbuild /v:m /nologo

artifacts:
- path: '**\TestResults.xml'

test_script:
- msbuild /t:test
